### ISSUE TITLE
Backups overlap when the job is restarted

### ISSUE THREAD

**Issue by jpalermo** [pivotal-cf/service-backup-release#3]
If a backup is running, and a bosh deploy updates the vm where service-backup is running, it leaves the backup running.

When service-backup starts up again, it does not detect that the backup is still running and starts a new one. This leads to the vm being overloaded while trying to process two backups at the same time.

This can also lead to pollution of the `service-backup.source_folder` directory.

It would be better if the monit stop of service-backup terminated the running backup before stopping itself.

**Comment by avade** [comment]
Would you also expect the cleanup executable to run?

**Comment by avade** [comment]
@jpalermo ping ^^^^^^

**Comment by jpalermo** [comment]
If cleanup normally runs after then it seems like a good idea, if cleanup is normally run before a backup run is started then it doesn't seem necessary.

**Comment by jpalermo** [comment]
FYI, we also run into problems when doing a stemcell update. Our job is still running, and still using the persistent disk, so bosh can't detach the disk.

**Comment by avade** [comment]
We have implemented a solution that sends a SIGTERM as part of the drain script.

The question we now have is "do you consider this a breaking change"?

**Comment by jpalermo** [comment]
Sorry, missed this message.

I don't think it's a breaking change. It would not have worked before anyway. Even if the backup finished before, service-backup release wouldn't have known to upload it anywhere.

**Comment by avade** [comment]
@jpalermo the latest service-backup release sends a SIGTERM to all running backup processes. See docs [here](https://docs.pivotal.io/svc-sdk/service-backup/18-1/#preparing-files)

**Comment by jpalermo** [comment]
Sorry it took us so long to verify. Looks good.
