### ISSUE TITLE
cleanup should happen before backups are taken

### ISSUE THREAD

**Issue by ndhanushkodi** [pivotal-cf/service-backup-release#5]
We ran into an issue where our backups failed, and never got cleaned up. When backups were restarted, due to the extra files on disk, there now wasn't enough free space to complete a backup.

Would it be better for service-backup to run the cleanup executable before starting a backup cycle, or is this something that we should be cleaning up manually when backups start?

**Comment by avade** [comment]
How about service-backup runs `cleanup-executable` in the failure scenario? 

Would that cause any issues for debugging?

**Comment by ndhanushkodi** [comment]
It might be valuable to not run the `cleanup-executable` on failure if the backup is successfully taken, but the upload phase fails. In that case, there is a valid backup on disk, and an operator who gets notified (if they have notifications enabled) would be able to take action manually to retrieve that successful backup from the disk.

We think this use case might be valuable to retain, and it's possible that other consumers of `service-backup-release` would value that functionality, so we'd prefer to do cleanup right before a new backup is taken, if it's possible for you to implement it. Thanks!

**Comment by avade** [comment]
@ndhanushkodi our current suggestion is for you to handle any cleanup in your backup executable before you run the actual backup. Does this sound plausible?

**Comment by deniseyu** [comment]
@ndhanushkodi I'm going to close out this issue as it seems like cleanup is possible without making changes to the service-backups release. If @avade's suggested solution isn't feasible please let us know. cc @mattmcneeney
