### ISSUE TITLE
S3 uploads may hang with large backup files

### ISSUE THREAD

**Issue by abg** [pivotal-cf/service-backup-release#8]
### Problem
In our environment we found backup with a configured s3 destination were hanging with `service-backup-release` v18.1.13.

Investigating we found, via strace, that the AWS cli was idle and blocking writing to file descriptor `1` (stdout):

```bash
# strace -s 65535 -p $(pidof -x aws) -ff
strace: Process 11465 attached with 2 threads
[pid 11469] write(1, "Completed 473.5 MiB/497.9 MiB (94.5 MiB/s) with 1 file(s) remaining \r", 69 <unfinished ...>
[pid 11465] futex(0x7fbce0000c10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff
```

We were able to reproduce this in a fresh environment by creating a backup artifact to upload of a few hundred MB and running a manual backup which similarly hung.

### Analysis
This seems to be related to https://github.com/pivotal-cf/service-backup/commit/c1e3571965fcf0d0d56e191adbd1bca20ace6036.  

What we believe is happening is that service-backup is attempting to wait for the aws cli to exit without having read all of the aws cli command output.  The aws cli in turn is blocking writing to a full pipe which will never be read.

We believe the following leads to the current hang:

- Service backup uses a [ProcessManager](https://github.com/pivotal-cf/service-backup/blob/3d433c8c358ec728714327dbb6c62f1e0062f403/process/manager.go) abstraction to manage command output external commands
  - This includes executing the aws CLI.
- [ProcessManager.Start() configures pipes](https://github.com/pivotal-cf/service-backup/blob/3d433c8c358ec728714327dbb6c62f1e0062f403/process/manager.go#L46-L55) to capture the output of the AWS cli
- [ProcessManager.Start() uses a bufio.Scanner](https://github.com/pivotal-cf/service-backup/blob/3d433c8c358ec728714327dbb6c62f1e0062f403/process/manager.go#L69) to process command output
- [bufio.Scanner has a default 64KiB line limit](https://golang.org/pkg/bufio/#MaxScanTokenSize) after which it stops scanning and sets an `ErrTooLong` error on the Scanner
- The AWS CLI outputs a series of progress information of the form `Completed 473.5 MiB/497.9 MiB (94.5 MiB/s) with 1 file(s) remaining \r`, but never emits a newline
- bufio.Scanner.Scan eventually fails after reading 64KiB of non-newline-terminated output, flags the scanner with [ErrTooLong](https://golang.org/pkg/bufio/#ErrTooLong)
  - This is currently [not checked by ProcessManager](https://github.com/pivotal-cf/service-backup/blob/3d433c8c358ec728714327dbb6c62f1e0062f403/process/manager.go#L70-L73)
- [ProcessManager proceeds to wait for the aws CLI to exit](https://github.com/pivotal-cf/service-backup/blob/3d433c8c358ec728714327dbb6c62f1e0062f403/process/manager.go#L73)
- The AWS CLI continues attempting to emit progress information and eventually blocks on the Linux 64KiB pipe capacity and so never exits.

Ultimately we have a hang which completely breaks uploading backups to S3 (at least).

### Workarounds
Rolling back to v18.1.11 before https://github.com/pivotal-cf/service-backup/commit/c1e3571965fcf0d0d56e191adbd1bca20ace6036 seemed promising.  Unfortunately we are already using xenial stemcells, and service-backup-release did not support xenial before #7 (v18.1.12+).

**Comment by ruthmaclean** [comment]
This issue is resolved in Service Backup [18.1.15](https://network.pivotal.io/products/service-backups-sdk)

Thanks!
